#!/usr/bin/python3

import requests
import json
from colorama import Fore
from time import sleep, localtime, strftime

#print(chr(27) + "[3J" + chr(27) + "[H" + chr(27) + "[2J", end="", flush=True)
#while True:

if __name__ == "__main__":

    timestr = strftime('%Y-%m-%d %H:%M:%S', localtime())


    try:
        r = requests.get('https://api.coinmarketcap.com/v1/ticker/')
        data = r.json()

#        print(chr(27) + "[3J" + chr(27) + "[H" + chr(27) + "[2J", end="", flush=True)
        print(timestr + "\n")
        for currency in data:
            if currency["symbol"] in ("ETH", "BTC", "ETC"):
                chg = float(currency["percent_change_24h"])
                prc = float(currency["price_usd"])
                color = Fore.RED if (chg < 0) else Fore.GREEN
                label = Fore.YELLOW+"%s: " % (currency["symbol"])
                value = Fore.WHITE+"${:4.2f}"+Fore.RESET
                change = color+" {:2.2f}%".format(chg)
                print(label + value.format(prc).ljust(18), change  + Fore.RESET)
    except:
#        print(chr(27) + "[3J" + chr(27) + "[H" + chr(27) + "[2J", end="", flush=True)
        print(timestr + "\n")
        print("Unable to connect")
#    sleep(10)
