#!/usr/bin/python3

import requests
from colorama import Fore
from time import localtime, strftime

if __name__ == "__main__":

    timestr = strftime('%Y-%m-%d %H:%M:%S', localtime())

    try:
        r = requests.get('https://api.coinmarketcap.com/v1/ticker/')
        data = r.json()

        print(timestr + "\n")
        for currency in data:
            if currency["symbol"] in ("ETH", "BTC", "ETC", "LTC"):
                chg = float(currency["percent_change_24h"])
                prc = float(currency["price_usd"])
                color = Fore.RED if (chg < 0) else Fore.GREEN
                label = Fore.YELLOW + "%s: " % (currency["symbol"])
                value = Fore.WHITE + "${:4.2f}" + Fore.RESET
                change = color + " {:2.2f}%".format(chg)
                print(label + value.format(prc).ljust(18), change + Fore.RESET)
    except:
        print(timestr + "\n")
        print("Unable to connect")
